services:
  door-status:
    pull_policy: build
    build:
      context: .
      dockerfile: Dockerfile
    container_name: door-status
    # ports:
      # - "3001:3001"
    restart: on-failure
    environment:
      NODE_ENV: production        # plus DATABASE_URL, etc.
    volumes:
      # Persist everything under /app/prisma (schema, generated client, SQLite file, etc.)
      - prisma-data:/app/prisma/data
    networks:
      - traefik_web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cssacommonroom.rule=Host(`cssa.ashl.dev`)"
      - "traefik.http.routers.cssacommonroom.entrypoints=websecure"
      - "traefik.http.services.cssacommonroom.loadbalancer.server.port=3001"
      - "traefik.http.routers.cssacommonroom.tls.certresolver=leresolver"

volumes:
  prisma-data:                    # ← named volume lives outside container life-cycle

networks:
  traefik_web:
    name: traefik_web
    external: true