-- CreateTable
CREATE TABLE "DoorStatus" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "status" TEXT NOT NULL DEFAULT 'closed',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
